<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <UsesChrysalisHttp>false</UsesChrysalisHttp>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Chrysalis\Butterfly.Chrysalis.Core\Butterfly.Chrysalis.Core.csproj" />
    <ProjectReference Include="..\..\..\src\Serialization\Butterfly.Serialization.Generators\Butterfly.Serialization.Generators.csproj" />
  </ItemGroup>

</Project>