<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..'))" />

  <!-- Workflows relies on reflection, dynamic code and reflection-based JSON/minimal APIs: not AOT compatible. -->
  <PropertyGroup>
    <IsAotCompatible>false</IsAotCompatible>
  </PropertyGroup>

</Project>