<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Scripting\Butterfly.Scripting.Chrysalis\Butterfly.Scripting.Chrysalis.csproj" />
    <ProjectReference Include="..\..\..\src\Scripting\Butterfly.Scripting.CSharp\Butterfly.Scripting.CSharp.csproj" />
    <ProjectReference Include="..\..\..\src\Chrysalis\Butterfly.Chrysalis.Binary\Butterfly.Chrysalis.Binary.csproj" />
    <ProjectReference Include="..\..\..\src\Chrysalis\Butterfly.Chrysalis.Rest\Butterfly.Chrysalis.Rest.csproj" />
  </ItemGroup>

</Project>
