<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\SystemInfo\Butterfly.SystemInfo.Chrysalis\Butterfly.SystemInfo.Chrysalis.csproj" />
    <ProjectReference Include="..\..\..\src\Chrysalis\Butterfly.Chrysalis.Binary\Butterfly.Chrysalis.Binary.csproj" />
    <ProjectReference Include="..\..\..\src\Chrysalis\Butterfly.Chrysalis.Rest\Butterfly.Chrysalis.Rest.csproj" />
  </ItemGroup>

</Project>
