using Butterfly.Serialization;
using System.Text;

namespace Butterfly.Chrysalis.Grpc
{
    /// <summary>
    /// The .proto (proto3) of a service, so clients in any language can be generated with protoc. Field numbers and
    /// enum values are the ones Chrysalis puts on the wire; members the profile hides are left out.
    /// </summary>
    public static class ProtoFile
    {
        public static string Generate(ChrysalisService service, SerializationProfile? profile = null)
        {
            ArgumentNullException.ThrowIfNull(service);
            profile ??= SerializationProfile.Default;

            var messages = new List<ObjectType>();
            var enums = new List<EnumType>();
            var seen = new HashSet<SerializableType>();
            var usesTimestamp = false;
            var usesStruct = false;
            var usesDuration = false;

            void Collect(SerializableType type)
            {
                switch (type)
                {
                    case ListType list:
                        Collect(list.Element);
                        break;
                    case MapType map:
                        Collect(map.Value);
                        break;
                    case DynamicType:
                        usesStruct = true;
                        break;
                    case EnumType enumeration when seen.Add(type):
                        enums.Add(enumeration);
                        break;
                    case ObjectType message when seen.Add(type):
                        messages.Add(message);
                        foreach (var field in message.Members.Where(member => member.IsVisibleIn(profile)))
                            Collect(field.Type);
                        break;
                    case { Kind: TypeKind.Timestamp }:
                        usesTimestamp = true;
                        break;
                    case { Kind: TypeKind.Duration }:
                        usesDuration = true;
                        break;
                }
            }

            foreach (var operation in service.Operations)
            {
                Collect(GrpcMessages.RequestType(operation));
                Collect(GrpcMessages.ResponseType(operation));
            }

            var proto = new StringBuilder();
            proto.AppendLine("// Generated by Butterfly.Chrysalis.");
            proto.AppendLine("syntax = \"proto3\";");
            proto.AppendLine();
            if (!string.IsNullOrEmpty(service.Namespace))
                proto.AppendLine($"package {service.Namespace};").AppendLine();
            if (usesTimestamp)
                proto.AppendLine("import \"google/protobuf/timestamp.proto\";");
            if (usesStruct)
                proto.AppendLine("import \"google/protobuf/struct.proto\";");
            if (usesDuration)
                proto.AppendLine("import \"google/protobuf/duration.proto\";");
            if (usesTimestamp || usesStruct || usesDuration)
                proto.AppendLine();

            proto.AppendLine($"service {service.Name} {{");
            foreach (var operation in service.Operations)
                proto.AppendLine($"  rpc {operation.Name} ({GrpcMessages.RequestType(operation).Name}) returns ({GrpcMessages.ResponseType(operation).Name});");
            proto.AppendLine("}");

            foreach (var message in messages)
            {
                proto.AppendLine().AppendLine($"message {message.Name} {{");
                foreach (var field in message.Members.Where(member => member.IsVisibleIn(profile)))
                {
                    var label = field.Type is ListType ? "repeated " : field.IsOptional && field.Type.IsScalar ? "optional " : "";
                    var comment = field.Type.Kind switch
                    {
                        TypeKind.Decimal => " // decimal, invariant culture",
                        TypeKind.Guid => " // GUID",
                        _ => ""
                    };
                    proto.AppendLine($"  {label}{TypeName(field.Type)} {SnakeCase(field.Name)} = {field.Number};{comment}");
                }
                proto.AppendLine("}");
            }

            foreach (var enumeration in enums)
            {
                // Enum values share the package scope in protobuf, hence the prefix; proto3 needs a zero value first.
                var prefix = ScreamingCase(enumeration.Name) + "_";
                proto.AppendLine().AppendLine($"enum {enumeration.Name} {{");
                if (!enumeration.Members.Any(value => value.Number == 0))
                    proto.AppendLine($"  {prefix}UNSPECIFIED = 0;");
                foreach (var value in enumeration.Members.OrderBy(value => value.Number == 0 ? 0 : 1))
                    proto.AppendLine($"  {prefix}{ScreamingCase(value.Name)} = {value.Number};");
                proto.AppendLine("}");
            }

            return proto.ToString();
        }

        private static string TypeName(SerializableType type) => type.Kind switch
        {
            TypeKind.Boolean => "bool",
            TypeKind.Int32 => "int32",
            TypeKind.Int64 => "int64",
            TypeKind.Double => "double",
            TypeKind.Decimal or TypeKind.Guid or TypeKind.String => "string",
            TypeKind.Bytes => "bytes",
            TypeKind.Timestamp => "google.protobuf.Timestamp",
            TypeKind.List => TypeName(((ListType)type).Element),
            TypeKind.Map => $"map<string, {TypeName(((MapType)type).Value)}>",
            TypeKind.Dynamic => "google.protobuf.Value",
            TypeKind.Duration => "google.protobuf.Duration",
            _ => type.Name
        };

        internal static string SnakeCase(string name)
        {
            var builder = new StringBuilder(name.Length + 4);
            for (var i = 0; i < name.Length; i++)
            {
                var c = name[i];
                if (char.IsUpper(c))
                {
                    // A new word starts at an upper-case letter after a lower-case one, or before one ("HTTPServer" -> http_server).
                    if (i > 0 && (char.IsLower(name[i - 1]) || (i + 1 < name.Length && char.IsLower(name[i + 1]) && char.IsUpper(name[i - 1]))))
                        builder.Append('_');
                    builder.Append(char.ToLowerInvariant(c));
                }
                else
                {
                    builder.Append(c);
                }
            }
            return builder.ToString();
        }

        private static string ScreamingCase(string name) => SnakeCase(name).ToUpperInvariant();
    }
}
