<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Chrysalis\Butterfly.Chrysalis.AspNetCore\Butterfly.Chrysalis.AspNetCore.csproj" />
  </ItemGroup>

</Project>